#! /usr/bin/env ruby

require "./lib/rubydrop"

# Check to make sure we aren't running in Windows
if RUBY_PLATFORM =~ /(win|w)32$/ then
	puts "Sorry, RubyDrop is currently only available for Unix/Linux."
	exit!
end

RubyDrop.new().run()